//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z3
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHPlantingWorker
    {
        public int ID { get; set; }
        public Nullable<int> Worker { get; set; }
        public Nullable<int> Greenhouse { get; set; }
    
        public virtual Greenhouses Greenhouses { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
