//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Greenhouses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Greenhouses()
        {
            this.GHPlantingWorker = new HashSet<GHPlantingWorker>();
            this.GreenhousePlanting = new HashSet<GreenhousePlanting>();
        }
    
        public int ID { get; set; }
        public string Greenhouse { get; set; }
        public Nullable<int> Size { get; set; }
        public string Description { get; set; }
        public Nullable<int> TypeOfGH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GHPlantingWorker> GHPlantingWorker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreenhousePlanting> GreenhousePlanting { get; set; }
        public virtual TypesGH TypesGH { get; set; }
    }
}
