//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z3
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreenhousePlanting
    {
        public int ID { get; set; }
        public Nullable<int> GreenhouseNum { get; set; }
        public Nullable<int> VegPlanting { get; set; }
        public Nullable<System.DateTime> PlantDate { get; set; }
    
        public virtual Greenhouses Greenhouses { get; set; }
        public virtual Vegatables Vegatables { get; set; }
    }
}
