//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PP042022Entities : DbContext
    {
        private static PP042022Entities context;
        public PP042022Entities()
            : base("name=PP042022Entities")
        {
        }

        static public PP042022Entities GetContext()
        {
            if (context == null)
                context = new PP042022Entities();
            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GHPlantingWorker> GHPlantingWorker { get; set; }
        public virtual DbSet<GreenhousePlanting> GreenhousePlanting { get; set; }
        public virtual DbSet<Greenhouses> Greenhouses { get; set; }
        public virtual DbSet<TypesGH> TypesGH { get; set; }
        public virtual DbSet<Vegatables> Vegatables { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
