//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vegatables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vegatables()
        {
            this.GreenhousePlanting = new HashSet<GreenhousePlanting>();
        }
    
        public int ID { get; set; }
        public string Vegetable { get; set; }
        public Nullable<int> RipeningPeriod { get; set; }
        public Nullable<int> FrutingPeriod { get; set; }
        public Nullable<int> DiePeriod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreenhousePlanting> GreenhousePlanting { get; set; }
    }
}
